name: simplevpn
description: SimpleVPN - DPI-resistant VPN client
publish_to: 'none'
version: 1.4.3+8

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  mobile_scanner: ^5.0.0
  shared_preferences: ^2.2.0
  flutter_secure_storage: ^9.0.0
  flutter_riverpod: ^2.4.0
  package_info_plus: ^8.0.0
  http: ^1.2.0
  crypto: ^3.0.0
  qr_flutter: ^4.1.0
  fl_chart: ^0.69.0
  app_links: ^6.0.0
  share_plus: ^10.0.0
  path_provider: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  generate: true

  fonts:
    - family: ArchivoBlack
      fonts:
        - asset: assets/fonts/ArchivoBlack-Regular.ttf
    - family: SpaceGrotesk
      fonts:
        - asset: assets/fonts/SpaceGrotesk-Regular.ttf
        - asset: assets/fonts/SpaceGrotesk-Medium.ttf
          weight: 500
        - asset: assets/fonts/SpaceGrotesk-Bold.ttf
          weight: 700
    - family: JetBrainsMono
      fonts:
        - asset: assets/fonts/JetBrainsMono-Regular.ttf
        - asset: assets/fonts/JetBrainsMono-Medium.ttf
          weight: 500
        - asset: assets/fonts/JetBrainsMono-Bold.ttf
          weight: 700
