name: simplevpn
description: SimpleVPN - DPI-resistant VPN client
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  mobile_scanner: ^5.0.0
  shared_preferences: ^2.2.0
  flutter_secure_storage: ^9.0.0
  flutter_riverpod: ^2.4.0
  package_info_plus: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
